// Server-side price catalog — extracted from the product ids used by Cart.add() across
// tables.html, basins.html, boards.html, plinths.html, gallery.html and sale.html.
// This is the ONLY source of truth for price at checkout — never trust a price sent by the client.
export const CATALOG = {
  'basin-beige': { name: "Warm Beige Basin", type: "Vessel Basin", price: 990 },
  'basin-carrara': { name: "White Carrara Basin", type: "Vessel Basin", price: 1190 },
  'basin-green': { name: "Dark Green Marble Basin", type: "Vessel Basin", price: 1090 },
  'basin-nero': { name: "Nero Marquina Basin", type: "Vessel Basin", price: 1050 },
  'basin-nero-marquina': { name: "Nero Marquina Basin", type: "Stone Basin", price: 850 },
  'basin-pietra-grey': { name: "Pietra Grey Basin", type: "Vessel Basin", price: 1350 },
  'basin-pink-onyx-shell': { name: "Pink Onyx Shell Basin", type: "Vessel Basin", price: 1490 },
  'basin-pink-purple-onyx': { name: "Pink Purple Onyx Basin", type: "Vessel Basin", price: 1890 },
  'basin-statuario': { name: "Statuario Marble Basin", type: "Vessel Basin", price: 1290 },
  'basin-tiger-onyx': { name: "Tiger Onyx Basin", type: "Vessel Basin", price: 1350 },
  'basin-white-carrara': { name: "White Carrara Basin", type: "Stone Basin", price: 850 },
  'basin-white-onyx': { name: "White Onyx Basin", type: "Vessel Basin", price: 1250 },
  'basin-yellow-onyx': { name: "Yellow Onyx Basin", type: "Vessel Basin", price: 1250 },
  'board-emerald-vein': { name: "Emerald Vein", type: "Serving Board", price: 99 },
  'board-green-onyx': { name: "Jade Cloud", type: "Serving Board", price: 99 },
  'board-india-green': { name: "Forest Stone", type: "Serving Board", price: 99 },
  'board-pink-storm': { name: "Pink Storm", type: "Serving Board", price: 99 },
  'board-teal-tide': { name: "Teal Tide", type: "Serving Board", price: 99 },
  'board-teal-tide-2': { name: "Teal Tide II", type: "Serving Board", price: 99 },
  'board-teal-tide-4': { name: "Teal Tide IV", type: "Serving Board", price: 99 },
  'board-volcanic-ash': { name: "Volcanic Ash", type: "Serving Board", price: 99 },
  'board-white-haven': { name: "White Haven", type: "Serving Board", price: 99 },
  'plinth-dekton-sirius-side': { name: "Dekton Sirius", type: "Side Plinth", price: 1500 },
  'plinth-florim': { name: "Florim", type: "Plinth", price: 3200 },
  'plinth-grey-porcelain-450': { name: "Grey Porcelain Side Plinth", type: "Side Plinth", price: 700 },
  'plinth-grey-porcelain-800': { name: "Grey Porcelain Plinth", type: "Plinth", price: 1499 },
  'plinth-grey-porcelain-side': { name: "Grey Porcelain Side Plinth", type: "Plinth", price: 700 },
  'plinth-indian-green-2': { name: "Indian Green Marble Plinth", type: "Plinth", price: 1499 },
  'plinth-navarro': { name: "Navarro Marble", type: "Plinth", price: 3499 },
  'plinth-rosso-africano-plinth': { name: "Rosso Africano Marble", type: "Plinth", price: 3800 },
  'plinth-rosso-africano-table-2': { name: "Rosso Africano Marble Table", type: "Coffee Table Plinth", price: 4900 },
  'plinth-rosso-levanto-plinth': { name: "Rosso Levanto Marble", type: "Plinth", price: 1400 },
  'plinth-verde-apli-table': { name: "Verde Apli Marble Table", type: "Coffee Table Plinth", price: 4000 },
  'rosso-bundle': { name: "Rosso Africano Bundle — Table + Plinth", type: "Bundle", price: 7000 },
  'table-amazon-vein-2': { name: "Amazon Vein II", type: "Coffee Table", price: 300 },
  'table-arctic-vein': { name: "Arctic Vein", type: "Coffee Table", price: 299 },
  'table-blue-slate': { name: "Blue Slate", type: "Coffee Table", price: 270 },
  'table-dark-current': { name: "Dark Current", type: "Coffee Table", price: 295 },
  'table-desert-crown': { name: "Desert Crown", type: "Lounge Table", price: 1999 },
  'table-desert-drift': { name: "Desert Drift", type: "Coffee Table", price: 250 },
  'table-desert-drift-2': { name: "Desert Drift 2.0", type: "Coffee Table", price: 320 },
  'table-desert-drift-ii': { name: "Desert Drift II", type: "Coffee Table", price: 250 },
  'table-gold-rush': { name: "Gold Rush", type: "Coffee Table", price: 300 },
  'table-golden-hour': { name: "Golden Hour", type: "Coffee Table", price: 329 },
  'table-jade-horizon': { name: "Jade Horizon", type: "Lounge Table", price: 2100 },
  'table-jade-jewel': { name: "Jade Jewel", type: "Coffee Table", price: 319 },
  'table-jade-rain': { name: "Jade Rain", type: "Coffee Table", price: 319 },
  'table-lunar-river': { name: "Lunar River", type: "Bedside Table", price: 1500 },
  'table-midnight-moon': { name: "Midnight Moon", type: "Lounge Table", price: 2159 },
  'table-midnight-river': { name: "Midnight River", type: "Coffee Table", price: 290 },
  'table-midnight-wave': { name: "Midnight Wave", type: "Coffee Table", price: 309 },
  'table-mountain-breeze': { name: "Mountain Breeze", type: "Coffee Table", price: 199 },
  'table-obsidian-storm': { name: "Obsidian Storm", type: "Lounge Table", price: 2040 },
  'table-patagonia-platinum': { name: "Patagonia Platinum", type: "Coffee Table", price: 349 },
  'table-pietra-noir': { name: "Pietra Noir", type: "Coffee Table", price: 270 },
  'table-sage-plateau': { name: "Sage Plateau", type: "Lounge Table", price: 1499 },
  'table-serpentine-storm': { name: "Serpentine Storm", type: "Coffee Table", price: 275 },
  'table-sunset-stone': { name: "Sunset Stone", type: "Coffee Table", price: 250 },
  'table-twin-jade': { name: "Twin Jade (Set of 2)", type: "Side Table", price: 2199 },
  'table-twin-jade-single': { name: "Twin Jade (Single)", type: "Side Table", price: 1199 },
  'table-white-haven': { name: "White Haven", type: "Coffee Table", price: 249 },
  'table-white-haven-lounge': { name: "White Haven Carrara Lounge Table", type: "Lounge Table", price: 1199 },
};
